### ISSUE TITLE
Files are pushed across into root, rather than their folder.

### ISSUE THREAD

**Issue by shadow7412** [Serverfrog/Bitburner-Plugin#13]
**Describe the bug**
Pushing to bitburner does not appear to respect folder structure.

**To Reproduce**
1. Create a folder in your jetbrains project
2. Create a .js file
3. This should sync over to bitburner
4. ls in the terminal - note that the script file is in the root directory instead of the intended subdirectory.

**Expected behavior**
All scripts should sync to their respective folders, with the root of the project acting as the root of the home server.

**Screenshots**
N/A

**Bitburner(please complete the following information):**
 - OS: [e.g. iOS] Manjaro Linux, KDE
 - Platform[e.g. steam] Steam
 - Version [e.g. 22] 0.0.2

**Comment by shadow7412** [comment]
This *might* be a linux specific issue - as I note the code that is supposed to deal with it here; https://github.com/Serverfrog/Bitburner-Plugin/blob/e9375c05a9cc6445ad279e9f3d8d95016dde390c/src/main/kotlin/com/github/serverfrog/bitburnerplugin/bitburner/PushToBitburner.kt#L48

**Comment by Serverfrog** [comment]
Can be, never ran Bitburner under Linux. But this specific line was already changed and the path upload is changed a bit but not currently released. 
The plugin was develop where Folders in Bitburner didn't worked properly so i waited (maybe a bit to long ;) )to look at them again when Bitburner fixed their issue with them

**Comment by shadow7412** [comment]
> but not currently released.

So I might have some luck if I run this version rather than the one in the jetbrains plugin repo?

**Comment by shadow7412** [comment]
Turns out I can't just import the zip file from github... mind giving me some instructions?

**Comment by shadow7412** [comment]
(or, if it's stable, maybe another release?)

**Comment by Serverfrog** [comment]
i would do another release, but i need some free time for that ;) also Jetbrains take their 2 days to approve the Updates
But to be honest i never tried to install it from the Zip here build. I would think it should work (because this Project was set up with the Template Jetbrains gives) but cant say for sure

**Comment by Serverfrog** [comment]
Another way would also be to just check it out and try to run the Test IDE and see if this works there. I have currently no Linux Desktop at hand

**Comment by shadow7412** [comment]
I'm cool with trying it - I just don't know how to install it :P

**Comment by Serverfrog** [comment]
The part in the Readme wont work?

**Comment by Serverfrog** [comment]
ahh no, it wont have the fix in it... yhea..

**Comment by Serverfrog** [comment]
i released a new version so either use now the v0.0.3 release ZIP or wait for jetbrains ;)

**Comment by shadow7412** [comment]
Tested, and working now. Thanks for the release :)

**Comment by Serverfrog** [comment]
Nice to know ;) Thank you for testing
