### ISSUE TITLE
Upgrade to IDEA 2022-2 needed

### ISSUE THREAD

**Issue by Zacch** [Serverfrog/Bitburner-Plugin#15]
**Describe the bug**
I upgraded to IntelliJ IDEA 2022.2 (Build #IU-222.3345.118, built on July 26, 2022) and found that the plugin does not run under this version. On the plugins preferences tab it says "Incompatible: requires IDE build 221.* or earlier".

**To Reproduce**
1. Upgrade to IntelliJ IDEA 2022.2
2. The plugin is marked as incompatible and no longer runs

**Expected behavior**
I would expect the plugin to run

**Bitburner**
 - OS: MacOS Monterey, 12.3.1 (running on an M1 MacBook Pro, but that doesn't matter :))
 - Platform: Steam
 - Version: BitBurner v1.7.0 (cfcdc254)
 - IDE Version: IntelliJ IDEA 2022.2, Build #IU-222.3345.118.

**Additional context**
Thank you so much for developing this plugin!

I guess it's most likely a matter of updating some config file and publishing a new version. Still, let me know if I can help!

**Comment by Serverfrog** [comment]
Should all be good ;)
Sadly it is not possible, even for such simple Plugin, to say that it does not matter if a new Version of IDEA comes out.
But if i touch the Plugin, i will update some of the Libs inside too in the same step.

**Comment by Serverfrog** [comment]
Should be available now!

**Comment by Zacch** [comment]
Works perfectly – awesome!
