### ISSUE TITLE
Compatibility with latest IntelliJ version

### ISSUE THREAD

**Issue by alxfhl** [Serverfrog/Bitburner-Plugin#18]
Thank you for providing this great plugin! Sadly it is only compatible with IntelliJ IDEA 2022.2 and older versions.
If it is not too much work, could you update it to the current version 2022.3 and the soon to be released 2023.1?

**Comment by Serverfrog** [comment]
Will do it during the course of the day.
Jetbrains want to have a value set until which build this Plugin is supported. so for every new version i need to re-release it with that value increased ;)  https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html

I will also update the Dependencies when im already on it

**Comment by Serverfrog** [comment]
This is now in the Approving Process of Jetbrains.
I Quote: 

> JetBrains is reviewing this update. Please expect it to be approved within two business days of the upload.

**Comment by alxfhl** [comment]
You are really fast, thank you :-)
